package org.example.backend.domain.project.enums;

public enum ServerStatus {
    INIT,
    SET_SWAP_MEMORY,
    UPDATE_PACKAGE,
    INSTALL_JDK,
    INSTALL_DOCKER,
    RUN_APPLICATION,
    INSTALL_NGINX,
    INSTALL_JENKINS,
    INSTALL_JENKINS_PLUGINS,
    SET_JENKINS_INFO,
    CREATE_JENKINS_JOB,
    CREATE_JENKINSFILE,
    CREATE_FRONTEND_DOCKERFILE,
    CREATE_BACKEND_DOCKERFILE,
    CREATE_WEBHOOK,
    FINISH,
    FAIL
}
