export const dummyBuilds = [
  {
    id: 119,
    title: 'MR 빌드',
    date: 'Apr 22, 2025',
    time: '11:30:02',
    status: 'SUCCESS',
    link: 'https://gitlab.com/example/119',
    tasks: [
      {
        no: 1,
        description: 'EC2 배포를 위한 설정',
        duration: '3hr 20min',
        status: 'Complete' as const,
      },
      {
        no: 2,
        description: '애플리케이션 환경 설정',
        duration: '2hr 10min',
        status: 'Complete' as const,
      },
      {
        no: 3,
        description: 'docker-compose 설정',
        duration: '1hr 45min',
        status: 'Complete' as const,
      },
      {
        no: 4,
        description: 'git clone',
        duration: '10min',
        status: 'Complete' as const,
      },
      {
        no: 5,
        description: '환경 변수 설정',
        duration: '15min',
        status: 'Fail' as const,
      },
      {
        no: 6,
        description: 'Nginx, HTTP 설정',
        duration: '-',
        status: 'Fail' as const,
      },
    ],
  },
  {
    id: 118,
    title: 'MR 빌드',
    date: 'Apr 21, 2025',
    time: '11:30:02',
    status: 'FAIL',
    link: 'https://gitlab.com/example/118',
    tasks: [
      {
        no: 1,
        description: 'SSL 인증서 발급',
        duration: '1hr 15min',
        status: 'Complete' as const,
      },
      {
        no: 2,
        description: 'nginx.conf 수정',
        duration: '45min',
        status: 'Complete' as const,
      },
      {
        no: 3,
        description: '방화벽 포트 개방',
        duration: '10min',
        status: 'Complete' as const,
      },
      {
        no: 4,
        description: '도메인 DNS 설정',
        duration: '-',
        status: 'In Progress' as const,
      },
      {
        no: 5,
        description: 'HTTPS 리다이렉트 테스트',
        duration: '-',
        status: 'In Progress' as const,
      },
    ],
  },
  {
    id: 117,
    title: 'MR 빌드',
    date: 'Apr 21, 2025',
    time: '11:30:02',
    status: 'SUCCESS',
    link: 'https://gitlab.com/example/118',
    tasks: [
      {
        no: 1,
        description: '도커 이미지 재빌드',
        duration: '30min',
        status: 'Complete' as const,
      },
      {
        no: 2,
        description: '캐시 무효화 적용',
        duration: '10min',
        status: 'Complete' as const,
      },
      {
        no: 3,
        description: 'CI 테스트 수행',
        duration: '15min',
        status: 'Complete' as const,
      },
      {
        no: 4,
        description: '서버 재시작',
        duration: '5min',
        status: 'Fail' as const,
      },
      {
        no: 5,
        description: 'HTTPS 리다이렉트 테스트',
        duration: '-',
        status: 'In Progress' as const,
      },
    ],
  },
  {
    id: 116,
    title: 'MR 빌드',
    date: 'Apr 21, 2025',
    time: '11:30:02',
    status: 'SUCCESS',
    link: 'https://gitlab.com/example/118',
    tasks: [
      {
        no: 1,
        description: '프로덕션 서버 환경 세팅',
        duration: '1hr 30min',
        status: 'Complete' as const,
      },
      {
        no: 2,
        description: '프론트엔드 빌드',
        duration: '1hr',
        status: 'Complete' as const,
      },
      {
        no: 3,
        description: '백엔드 마이그레이션',
        duration: '25min',
        status: 'Complete' as const,
      },
      {
        no: 4,
        description: '엔드포인트 점검',
        duration: '10min',
        status: 'In Progress' as const,
      },
      {
        no: 5,
        description: 'HTTPS 리다이렉트 테스트',
        duration: '-',
        status: 'In Progress' as const,
      },
    ],
  },
  {
    id: 115,
    title: 'MR 빌드',
    date: 'Apr 21, 2025',
    time: '11:30:02',
    status: 'SUCCESS',
    link: 'https://gitlab.com/example/118',
    tasks: [
      {
        no: 1,
        description: 'SSL 인증서 발급',
        duration: '1hr 15min',
        status: 'Complete' as const,
      },
      {
        no: 2,
        description: 'nginx.conf 수정',
        duration: '45min',
        status: 'Complete' as const,
      },
      {
        no: 3,
        description: '방화벽 포트 개방',
        duration: '10min',
        status: 'Complete' as const,
      },
      {
        no: 4,
        description: '도메인 DNS 설정',
        duration: '-',
        status: 'In Progress' as const,
      },
      {
        no: 5,
        description: 'HTTPS 리다이렉트 테스트',
        duration: '-',
        status: 'In Progress' as const,
      },
      {
        no: 6,
        description: 'SSL 인증서 발급',
        duration: '1hr 15min',
        status: 'Complete' as const,
      },
      {
        no: 7,
        description: 'nginx.conf 수정',
        duration: '45min',
        status: 'Complete' as const,
      },
      {
        no: 8,
        description: '방화벽 포트 개방',
        duration: '10min',
        status: 'Complete' as const,
      },
      {
        no: 9,
        description: '도메인 DNS 설정',
        duration: '-',
        status: 'In Progress' as const,
      },
      {
        no: 10,
        description: 'HTTPS 리다이렉트 테스트',
        duration: '-',
        status: 'In Progress' as const,
      },
    ],
  },
  {
    id: 114,
    title: 'MR 빌드',
    date: 'Apr 21, 2025',
    time: '11:30:02',
    status: 'FAIL',
    link: 'https://gitlab.com/example/118',
    tasks: [
      {
        no: 1,
        description: 'Swagger 문서 자동화',
        duration: '40min',
        status: 'Complete' as const,
      },
      {
        no: 2,
        description: 'API 서버 배포',
        duration: '35min',
        status: 'Fail' as const,
      },
      {
        no: 3,
        description: '응답 시간 테스트',
        duration: '-',
        status: 'In Progress' as const,
      },
      {
        no: 4,
        description: '도메인 DNS 설정',
        duration: '-',
        status: 'In Progress' as const,
      },
      {
        no: 5,
        description: 'HTTPS 리다이렉트 테스트',
        duration: '-',
        status: 'In Progress' as const,
      },
    ],
  },
  {
    id: 113,
    title: 'MR 빌드',
    date: 'Apr 21, 2025',
    time: '11:30:02',
    status: 'SUCCESS',
    link: 'https://gitlab.com/example/118',
    tasks: [
      {
        no: 1,
        description: 'npm audit fix',
        duration: '10min',
        status: 'Complete' as const,
      },
      {
        no: 2,
        description: '라이브러리 테스트 수행',
        duration: '50min',
        status: 'Complete' as const,
      },
      {
        no: 3,
        description: '배포 테스트',
        duration: '20min',
        status: 'Complete' as const,
      },
      {
        no: 4,
        description: '도메인 DNS 설정',
        duration: '-',
        status: 'In Progress' as const,
      },
      {
        no: 5,
        description: 'HTTPS 리다이렉트 테스트',
        duration: '-',
        status: 'In Progress' as const,
      },
    ],
  },
  {
    id: 112,
    title: 'MR 빌드',
    date: 'Apr 21, 2025',
    time: '11:30:02',
    status: 'SUCCESS',
    link: 'https://gitlab.com/example/118',
    tasks: [
      {
        no: 1,
        description: '이미지 압축',
        duration: '15min',
        status: 'Complete' as const,
      },
      {
        no: 2,
        description: 'JS 번들 크기 축소',
        duration: '20min',
        status: 'Complete' as const,
      },
      {
        no: 3,
        description: 'Lighthouse 검사',
        duration: '8min',
        status: 'In Progress' as const,
      },
      {
        no: 4,
        description: '도메인 DNS 설정',
        duration: '-',
        status: 'In Progress' as const,
      },
      {
        no: 5,
        description: 'HTTPS 리다이렉트 테스트',
        duration: '-',
        status: 'In Progress' as const,
      },
    ],
  },
];
